const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2348165846414",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUplcUtVcnpTbVZIZndGZjYzSWpaTVQwN3VQTjZqcTFMYzA5QnNjMnRHMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic3Y3ZEJ5dGdtSnFNeUdLNUgvSEtGbHlDRG9IVXdiN0EvbDQ1Mk1JSHpncz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1SUJJNUJOS1Y5NUtmdEEyZWNjeEQ5MVJXTHN2K241Q2IzUXQ0NG91Z1c0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVSmpJbUoxVTB0dWc4NDBkZ3ZRbTdTZkpUNUJEZ1FNNE5vREcwMG5vbVRVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldPMFlHbUlITTVyeHJlSEV1V0wzZUpaa3IrbXZrRnAwb1F5U1lYa2JBM0E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjVxN0NTRm1nWVFEMFRXNDZoK2xGTWk3SFpKUXFDRE42TEg2L0VRNVR1blU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMERPc3FWUVU0a3RHUFkySytOcEdySkh0MU1Md2MyTXRML2xkajhFeGdYVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSFg4cjEvamZHMnB1R0dzR2NCcDhRRkk1KytRalVNaU9vbG9VeWwvWXRYWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjEvNlNnR2sybkVFdVE0bkJ0UDNUYzBtMnBBMkpvcXNzT1diNTJWcWlSdmNvMFNNL1JLMS94d1dDNjlUWkhLRklJbnRsUy9BMlhBNlBGYjJCY2RLb0RBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTU4LCJhZHZTZWNyZXRLZXkiOiJXSTJ6TlByZzV2RzFJTHNjWk51WGNiQVhUc2dmMjhaYWZUMXJWSngvT2pBPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI2Mzc3ODk4NDYzM0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJCM0I0OTM3N0JBMzY0ODgwM0I4Qzk4NEU5RjVFQTc5NSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM3OTA4NzYxfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJRUkxBWEMzVCIsIm1lIjp7ImlkIjoiMjYzNzc4OTg0NjMzOjIzQHMud2hhdHNhcHAubmV0IiwibGlkIjoiMjUyNTc4ODM5NDA4ODg5OjIzQGxpZCIsIm5hbWUiOiLqp4HgvJLgvLvimKzgvZEg8J2VrfCdlo7wnZaMIPCdlpjwnZaS8J2WlPCdlpDwnZaKIOC9jOKYrOC8uuC8kuqngiJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDT1h5Z1pJREVJakUyYndHR0FNZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiVWszRTdtb0lxNER3SUtLdmd0dWw1aUlzOWJvUnU5azZMdEg4RkxjYndXZz0iLCJhY2NvdW50U2lnbmF0dXJlIjoid2lmUmZEN3ZmV3lqRTNQd05Rbzh2bUNQNkgrZUZrWllqaWNPdVBXdUN4elJKaFdtTDFLb1NLRHJvcGt3dE84V2l1WWVLb1dNUVNyd1ZybFJvT0lMQ2c9PSIsImRldmljZVNpZ25hdHVyZSI6IkxmY2d5ZEtYMVRXNXU3dzdEWnYxemRXV2dQQlIzY0xJOGlnaFNWWkpxSThxUE10UWw5NmJscFc3cGZuaEg4MW00cGxSWnJndmVEMlpyZFFhckpmUEJRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjYzNzc4OTg0NjMzOjIzQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlZKTnhPNXFDS3VBOENDaXI0TGJwZVlpTFBXNkVidlpPaTdSL0JTM0c4Rm8ifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBMElFZz09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNzkwODc1NywibGFzdFByb3BIYXNoIjoiMkc0QW11IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFDcUUifQ==",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
